using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using lifelogic;
using System.Collections.Generic;
using System.Linq;

namespace lifetest
{
  [TestClass]
  public class GridTests
  {
    [TestMethod]
    public void TickTest3x3Simple()
    {
      Grid g = new Grid(3, new _3x3factoryTriCorn());
      g.Initialize();
      g.Tick();

      // Should all be dead except center square
      foreach (PlanerCoordinate coordinate in g.GetCoordinates())
      {
        // Since this list was generated by the grid, all
        // of the coordinates should be valid.
        IEntity e = g.GetEntityAt(coordinate);
        if (coordinate.x == 1 && coordinate.y == 1)
        {
          Assert.IsTrue(e.Alive);
        }
        else
        {
          Assert.IsFalse(e.Alive);
        }
      }
    }
  }
}
